# Generated by Django 4.2.2 on 2023-07-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendance_attendance_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attendance'),
        ),
    ]
